# Tests building lazbuild using fplazup on Windows 32, Windows 64, Linux 64, MacOS 64 and AArch64 (cross compiled)
# Builds FPC 3.2.0 & Lazarus trunk but reverts to a known revision that compiles (64045).

name: Test

on: push

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: 'Windows 32'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-i386-win32.exe'
            fpcup-opt: '--fpcVersion="stable.gitlab" --lazVersion="trunk.gitlab"'
            
          - os: windows-latest
            name: 'Windows 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-x86_64-win64.exe'
            fpcup-opt: '--fpcVersion="stable.gitlab" --lazVersion="trunk.gitlab"'

          - os: ubuntu-latest
            name: 'Linux 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-x86_64-linux'
            fpcup-opt: '--fpcVersion="stable.gitlab" --lazVersion="trunk.gitlab"'

          - os: macos-latest
            name: 'MacOS 64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-x86_64-darwin'
            fpcup-opt: '--fpcVersion="stable.gitlab" --lazVersion="trunk.gitlab"'

          - os: ubuntu-latest
            name: 'AArch64'
            fpcup-url: 'https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-x86_64-linux'
            fpcup-opt: '--fpcVersion="stable.gitlab" --lazVersion="trunk.gitlab"'

    steps:
    - name: Install Dependencies (Ubuntu)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -m -y install libgtk2.0-dev libpango1.0-dev
    - name: Install Lazarus
      run: |
        curl --retry 5 -L -o fpcup ${{ matrix.config.fpcup-url }}
        chmod +x fpcup
        mkdir lazarus
        ./fpcup --installdir=lazarus ${{ matrix.config.fpcup-opt }} --only=docker --noconfirm --verbose
    - name: Install AArch64 Cross Compiler
      if: matrix.config.name == 'AArch64'
      run: |
        ./fpcup --installdir=lazarus --ostarget=linux --cputarget=aarch64 --only="FPCCleanOnly,FPCBuildOnly" --autotools --noconfirm --verbose
    - name: Test
      run: |
        ./lazarus/lazarus/lazbuild --help
